### ISSUE TITLE
Gating: Cropped Colorectal Issues

### ISSUE THREAD

**Issue by thejohnhoffer** [labsyspharm/minerva_analysis#100]
@kruegert  shared [this synapse link](https://www.synapse.org/#!Synapse:syn26304730/files/) to address an issue that @nchuynh  saw with outlines on the gating branch. I'm not able to reproduce his issue, but I see another one.

The whole-cell mode transitions smoothly while sliding:
![whole cell mode is ok)](https://user-images.githubusercontent.com/9781588/167006633-b6d645fe-379c-47c7-aca3-ceaddc95c289.gif)

While the outline mode transitions incorrectly (too abruptly):
![edge mode is broken](https://user-images.githubusercontent.com/9781588/167006730-53387920-380d-46a7-ae43-34e0b9edf03d.gif)

I should be able to sort this issue out myself. It seems to be a fragment shader (WebGL / GLSL) issue. However, I'm not seeing the issue @nchuynh  demonstrated. It seems this dataset does not have the empty inter-cell spacing characteristic of his demo. It would be good to verified that these files are indeed the same.

**Comment by thejohnhoffer** [comment]
To verify that the mask files are identical, run:

```
sha256sum crop-mask-crc01-097-096.tif 
```

and ensure the output matches:

```
a9e438c6f7d5f402a608af2b0e546aa424fad9115b4eab68faddeb67bbc91ab4  crop-mask-crc01-097-096.tif
```

**Comment by nchuynh** [comment]
Hey John, I pulled your recent commits and unfortunately I still see the issue with the outlines.

The dataset from the synapse link is the same as the one I showed, but I actually see this issue with every dataset, including Tuulia's that I shared with you.

I went back through your previous commits and found 3 points where the outlines changed. Starting with c11bdbb, I see the current outline issue.

https://user-images.githubusercontent.com/51902642/167311579-c320e305-6887-4123-876e-bbc47f02d6d9.mov

Before that, starting with f5b94c9 up to fc9419b, the outlines were thicker in the zoomed out view.

https://user-images.githubusercontent.com/51902642/167311601-bbc6c925-83e9-45ee-ac84-16b9f5a355e2.mov

And up to 8b9894f, the outlines looked normal.

https://user-images.githubusercontent.com/51902642/167311605-217d22a2-72c9-4753-8071-57b152efe5f5.mov

**Comment by kruegert** [comment]
Hm can't confirm that (2-fc9419b.mov) on my end.
For me it looks great with the cropped sardana dataset from synapse (see below)
Filtering is fast but panning and zooming is currently slow when the segmentation mask is rendered.

https://user-images.githubusercontent.com/31503434/167419831-0e827441-b79f-402d-8dd7-7399d2dc4006.mp4
