### ISSUE TITLE
Nearest Cells Filter to show values

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/minerva_analysis#32]
Showing min and max values of the histogram (x axis)
![image](https://user-images.githubusercontent.com/31503434/106759788-24015680-6601-11eb-9d86-bd4fdbc518ab.png)

+Rename filter into: Cell Intensity Histogram. The term nearest cells fits no nearly all filters.

**Comment by jessupjs** [comment]
Updating img:

<img width="589" alt="Screen Shot 2021-04-06 at 9 11 16 PM" src="https://user-images.githubusercontent.com/36556988/113796203-ae0e8e00-971c-11eb-9673-cc5a5c95a2f1.png">
